version: '3.8'
services:
  web:
    build: .
    ports:
    - "5001:5000"
    volumes:
    - .:/opt
    links:
    - mongo
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: siesta3
    volumes:
      - mongo-data:/data/db
      - mongo-configdb:/data/configdb


volumes:
  mongo-data:
    driver: local
  mongo-configdb:
